export const lossBlurbs = [
  'How the mighty have fallen!',
  "Well, that didn't go as planned.",
  'Defeat looks good on you.',
  'Welcome back to Earth, superstar.',
  'Guess who forgot how to win?',
  'Victory just unfollowed you.',
  'Better luck next millennium.',
  'You came, you saw, you lost spectacularly.',
  'Achievement unlocked: Epic Fail.',
  'Is losing your new hobby?',
  'Your fans called—they want their cheers back.',
  'Who knew greatness expired this quickly?',
  'Have you tried turning your skills off and on again?',
  "Legend has it, you're still losing.",
  "You're on fire! Oh wait, that's just the dumpster.",
  'It takes talent to lose like that.',
  "Look on the bright side—at least you're consistent.",
  "This week's performance: Rated Ouch.",
  "Can't win 'em all—or any, apparently.",
  'Even your shadow abandoned you after that one.',
  'Champagne dreams, soda reality.',
  "Bold strategy, losing. Let's see if it pays off.",
  'Breaking news: You still lost.',
  'You just earned a participation badge.',
  'Spoiler alert: You lost again.',
  'Are you allergic to winning?',
  'Congrats, you mastered losing!',
  'At least your losing streak is impressive.',
  'So close yet so hilariously far.',
  'That was painful. Do it again.',
  'You win some, you lose a lot more.',
  'Still better than nothing... barely.',
  'Ouch, the scoreboard just laughed at you.',
  "Greatness called; it's not coming back.",
  'Welcome to the hall of shame.',
  'Oops, you dropped your dignity.',
  'Forget winning—have you considered knitting?',
  "You almost had it! Narrator: They didn't.",
  'Even losers are judging you now.',
  'Your skills took an early retirement.',
  'Even your imaginary friends left after that.',
  'The other team says thanks for showing up.',
  'Winning was so last season.',
  "Don't worry; there's always next loss.",
  'Achievement unlocked: New Low.',
  'Game over. Insert skill to continue.',
  'Did you practice losing, or is this natural talent?',
  "You're the reason trophies cry.",
  'You were supposed to lose gracefully—not this badly.',
  'Next time, try playing with your eyes open.',
  "Guess the game wasn't ready for your greatness.",
  'Achievement unlocked: Consistent Disappointment.',
  "Looks like the 'W' button broke.",
  'At least losing suits you.',
  "You put the 'L' in legendary.",
  "It's not losing; it's strategic reverse winning.",
  "That wasn't just a loss—it was art.",
  'Winning called in sick today.',
  'Your win rate just filed for bankruptcy.',
  'Apparently losing is your new superpower.',
  'Even gravity feels sorry for you after that drop.',
  'The scoreboard demands an apology.',
  "Maybe next time, don't press pause on talent.",
  'Your win streak is in negative numbers now.',
  "Today's forecast: heavy losing with a chance of shame.",
  'New high score in losing. Impressive!',
  'Victory was within reach—and you tripped.',
  "You're redefining the term 'epic fail'.",
  'Try harder next week—or at least try.',
  'Better update your LinkedIn: Professional Loser.',
  'Even your luck rage quit after this game.',
  'You have the right to remain defeated.',
  'That loss was so brutal, historians will study it.',
  "Time to put 'professional losing' on your resume.",
  'Achievement unlocked: Ultimate Underdog.',
  "Don't give up—oh wait, maybe do.",
  'Lost again? You must be going for a record.',
  'Your dignity left halfway through the game.',
  "Don't feel bad; losing is your trademark now.",
  'You made losing fashionable again.',
  'Did you confuse losing with winning again?',
  "Even your GPS can't find victory.",
  'Practice makes perfect... at losing.',
  'Guess your skills are in vacation mode.',
  'Achievement unlocked: Lifetime membership in Losers Club.',
  "Today's special: all you can lose buffet.",
  'Even losers ask how you lose so often.',
  'Losing again? Groundbreaking.',
  'Maybe try easier games? Like breathing.',
  "You're officially the poster child for losses.",
  'Turns out, your talent has left the chat.',
  "You can't spell legendary without 'L'.",
  "At least you're reliable... reliably losing.",
  "Maybe next week you'll upgrade from tragic to mediocre.",
  'Losing again—what a time to be alive!',
  'Next time, try bribing the scoreboard.',
];

// Function to get a random blurb
export function getRandomBlurb(): string {
  const randomIndex = Math.floor(Math.random() * lossBlurbs.length);
  return lossBlurbs[randomIndex];
}
