import Head from 'next/head';
import Layout from '@/components/Layout';
import Detail from '@/components/DetailView';
import { NextPageWithLayout } from './_app';
import type { ReactElement } from 'react';

const DetailView: NextPageWithLayout = () => {
  return (
    <div className='bg-[#310639]'>
      <Head>
        <title>Detail Scoring</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='animate-fadeUp'>
        <Detail />
      </main>
    </div>
  );
};

DetailView.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default DetailView;
