import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Detail.module.css';
import HeaderSection from '@/components/header';
import Detail from '@/components/detailView';

const inter = Inter({ subsets: ['latin'] });

export default function DetailView() {
  return (
    <div className={styles.detailViewLayout}>
      <Head>
        <title>Detail Scoring</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <HeaderSection title='Detailed Player Score' />
        <Detail />
        <footer>
          <p>Built by Theunis Duminy & Johan Smal.</p>
        </footer>
      </main>
    </div>
  );
}
