import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import HeaderSection from '@/components/header';
import StandingsTable from '@/components/standingsTable';
import Buttons from '@/components/buttons';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Salty Spur Draft Standings</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <HeaderSection />
        <StandingsTable />
        <Buttons />
        <footer>
          <p>Built by Theunis Duminy.</p>
        </footer>
      </main>
    </div>
  );
}
