import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import HeaderSection from '@/components/header';
import StandingsTable from '@/components/standingsTable';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Salty Spur Draft Standings</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <HeaderSection />
        <StandingsTable />
        {/* <div class='buttons'>
          <a class='links' href='https://draft.premierleague.com' target='_blank'>
            Fantasy draft
          </a>
          <a class='links' href='/scoring' target='_self'>
            Scoring rules
          </a>
          <a class='links' href='/detail' target='_self'>
            Detailed view
          </a>
        </div> */}
      </main>
    </>
  );
}
