import Head from 'next/head';
import Layout from '@/components/Layout';
import StandingsTable from '@/components/StandingsTable';
import Buttons from '@/components/Buttons';
import { NextPageWithLayout } from './_app';
import type { ReactElement } from 'react';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Salty Spur Draft Standings</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='text-white flex item-center min-h-full animate-fadeUp'>
        <StandingsTable />
        <Buttons />
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
